parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: builder
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: d7cc3ccae320c60bca9e8fa0d35ad9e0a862557e
    socket_host: ws://builder.vagrant
    socket_port: 8080
    socket_databases: databases
    socket_instances: instances
    portal_url: builder.vagrant