services:
    app.builder.database.action.create:
        class: BuilderBundle\WebSocket\Channels\Databases\Actions\CreateAction
        arguments:
            databaseService: '@app.builder.service.database'

    app.builder.database.action.synchronize:
        class: BuilderBundle\WebSocket\Channels\Databases\Actions\SynchronizeAction
        arguments:
            databaseService: '@app.builder.service.database'

    app.builder.database.action.delete:
        class: BuilderBundle\WebSocket\Channels\Databases\Actions\DeleteAction
        arguments:
            databaseService: '@app.builder.service.database'

    app.builder.instance.action.create:
        class: BuilderBundle\WebSocket\Channels\Instances\Actions\CreateAction
        arguments:
            databaseService: '@app.builder.service.instance'

    app.builder.instance.action.synchronize:
        class: BuilderBundle\WebSocket\Channels\Instances\Actions\SynchronizeAction
        arguments:
            databaseService: '@app.builder.service.instance'

    app.builder.instance.action.delete:
        class: BuilderBundle\WebSocket\Channels\Instances\Actions\DeleteAction
        arguments:
            databaseService: '@app.builder.service.instance'