services:
    app.builder.websocket.channel.databases:
        class: BuilderBundle\WebSocket\Channels\Databases\DatabasesChannel
        arguments: ['@app.builder.factory.action.database', '@app.builder.service.params_validator', '@app.builder.service.websocket.authentication']

    app.builder.websocket.channel.instances:
        class: BuilderBundle\WebSocket\Channels\Instances\InstancesChannel
        arguments: ['@app.builder.factory.action.instances', '@app.builder.service.params_validator', '@app.builder.service.websocket.authentication']