services:
  app.builder.listener.exception:
    class: BuilderBundle\Listener\ExceptionListener
    arguments: ['@translator.default', '%kernel.environment%']
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  app.builder.listener.authentication:
    class: BuilderBundle\Listener\AuthenticationListener
    arguments: ['@app.builder.model.authentication']
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
