services:
    app.builder.model.user:
        class: BuilderBundle\Model\UserModel
        arguments: ['@app.builder.factory.user', '@app.builder.repository.user']

    app.builder.model.project:
        class: BuilderBundle\Model\ProjectModel
        arguments: ['@app.builder.factory.project', '@app.builder.repository.project']
