services:
    app.builder.model.user:
        class: BuilderBundle\Model\UserModel
        arguments: ['@app.builder.factory.user', '@app.builder.repository.user']

    app.builder.model.project:
        class: BuilderBundle\Model\ProjectModel
        arguments: ['@app.builder.factory.project', '@app.builder.repository.project', '%kernel.root_dir%']

    app.builder.model.checklist_item:
        class: BuilderBundle\Model\ChecklistItemModel
        arguments: ['@app.builder.factory.checklist', '@app.builder.repository.checklist_item']

    app.builder.model.checklist:
        class: BuilderBundle\Model\ChecklistModel
        arguments: ['@app.builder.factory.checklist', '@app.builder.repository.checklist', '@app.builder.model.checklist_item']

    app.builder.model.database:
        class: BuilderBundle\Model\DatabaseModel
        arguments: ['@app.builder.factory.database', '@app.builder.repository.database']

    app.builder.model.instance:
        class: BuilderBundle\Model\InstanceModel
        arguments: ['@app.builder.factory.instance', '@app.builder.repository.instance', '@app.builder.model.database', '@app.builder.model.project', '@app.builder.model.checklist', '@app.builder.model.user', '@app.builder.service.jira', '%portal_url%']

    app.builder.model.user_token:
        class: BuilderBundle\Model\UserTokenModel
        arguments:
          userTokenRepository: '@app.builder.repository.user_token'