services:
    app.builder.repository.user:
        class: BuilderBundle\Repository\UserRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
          - BuilderBundle\Entity\User

    app.builder.repository.project:
        class: BuilderBundle\Repository\ProjectRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
          - BuilderBundle\Entity\Project

    app.builder.repository.checklist:
        class: BuilderBundle\Repository\ChecklistRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
          - BuilderBundle\Entity\Checklist

    app.builder.repository.checklist_item:
        class: BuilderBundle\Repository\ChecklistItemRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
          - BuilderBundle\Entity\ChecklistItem

    app.builder.repository.database:
        class: BuilderBundle\Repository\DatabaseRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
          - BuilderBundle\Entity\Database

    app.builder.repository.instance:
        class: BuilderBundle\Repository\InstanceRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
          - BuilderBundle\Entity\Instance

    app.builder.repository.user_token:
        class: BuilderBundle\Repository\UserTokenRepository
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
          - BuilderBundle\Entity\UserToken