services:
    app.builder.repository.user:
        class: BuilderBundle\Repository\UserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
          - BuilderBundle\Entity\User