services:
    app.builder.service.register:
        class: BuilderBundle\Services\SecurityService
        arguments:
          userModel: '@app.builder.model.user'

    app.builder.service.user:
        class: BuilderBundle\Services\UserService
        arguments:
          userModel: '@app.builder.model.user'
