services:
    app.builder.service.register:
        class: BuilderBundle\Services\SecurityService
        arguments: ['@app.builder.model.user']

    app.builder.service.user:
        class: BuilderBundle\Services\UserService
        arguments: ['@app.builder.model.user']

    app.builder.service.file_finder:
        class: BuilderBundle\Services\FileFinderService
        arguments: ['%kernel.root_dir%']

    app.builder.service.database:
        class: BuilderBundle\WebSocket\Services\DatabaseService
        arguments: ['@app.builder.model.project','@app.builder.model.database', '%kernel.root_dir%']

    app.builder.service.instance:
        class: BuilderBundle\WebSocket\Services\InstanceService
        arguments: ['@app.builder.model.instance', '@app.builder.model.checklist', '%kernel.root_dir%', '%portal_url%']

    app.builder.service.params_validator:
        class: BuilderBundle\WebSocket\Settings\ParamsValidator

    app.builder.service.websocket.authentication:
        class: BuilderBundle\WebSocket\Services\WebSocketAuthentication
        arguments: ['@app.builder.model.authentication']

    app.builder.service.jira:
        class: BuilderBundle\Services\JiraService
        arguments: ['@app.builder.model.project']