services:
    app.builder.service.register:
        class: BuilderBundle\Services\SecurityService
        arguments: ['@app.builder.model.user']

    app.builder.service.user:
        class: BuilderBundle\Services\UserService
        arguments: ['@app.builder.model.user']

    app.builder.service.file_finder:
        class: BuilderBundle\Services\FileFinderService
        arguments: ['%kernel.root_dir%']